### ISSUE TITLE
Fill out

### ISSUE THREAD

**Issue by RichardLitt** [fabianlischka/InfoSec101#9]
This is an introduction. You need text explaining your purpose and what you're talking about. Otherwise, it just jumps right into list form and I don't want to read it all.

**Comment by fabianlischka** [comment]
Hi Richard, did I send you 
http://fabianlischka.github.io/InfoSec101
or
http://fabianlischka.github.io/InfoSec101/p1-InfoSec101/
?

The former is supposed to be an introduction. It's also linked under "introduction" in the menu. 

More suggestions much appreciated!

Greetings from Nusa Lembongan,
Fab

**Comment by RichardLitt** [comment]
Ah. That makes more sense. Looks good man!
